site_name: RingCentral Integration for HubSpot
site_url: https://github.com/ringcentral/ringcentral-integration-for-hubspot
repo_url: https://github.com/ringcentral/ringcentral-integration-for-hubspot.git
edit_uri: tree/master/docs
docs_dir: docs

plugins:
  - git-committers:
      repository: ringcentral/ringcentral-integration-for-hubspot
      branch: master
  - bootstrap-tables

theme:
  name: ringcentral
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

pages:
- 'Primary':
  - 'Overview':
    - 'Getting Started': index.md
    - 'Comparison': features-compare.md
  - 'Marketplace App':
    - 'Overview': marketplace-app/index.md
  - 'Browser Extension':
    - 'Overview': browser-extension/index.md
    - 'Installation': browser-extension/install.md
    - 'Customization': browser-extension/developers.md
    - 'About the Extension': browser-extension/about.md
- 'Secondary':
  - 'RingCentral Labs': labs.md
