site_name: RingCentral Integration for HubSpot
site_url: https://github.com/grokify/ringcentral-integration-for-hubspot
repo_url: https://github.com/grokify/ringcentral-integration-for-hubspot.git
docs_dir: docs
theme: readthedocs

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
nav:
- 'Overview': index.md
- 'Chrome Extension': chrome-extension/index.md
- 'Installation': chrome-extension/install.md
